version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "scikit-learn"
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "pre-commit"

