version: 2

python:
  install:
    - requirements: doc/docs_requirements.txt
    - requirements: requirements/prod.txt
    - method: pip
      path: .

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
   configuration: doc/conf.py

submodules:
  include: all
  recursive: true
