name: Tox
on: [push, pull_request]

permissions:
  contents: read

jobs:
  linting_and_docs:
    runs-on: ubuntu-latest
    name: Linting and Docs
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          submodules: true
      - name: Install third-party tools
        run: |
          sudo apt-get update
          sudo apt-get install cmake libenchant-2-dev
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install pandoc
      - name: Setup Python
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
        with:
          version: latest
          python-version: '3.13'
          cache-dependency-glob: |
            **/pyproject.toml
      - name: Install Tox
        run: uv tool install tox --with tox-uv
      - name: Run Tox
        env:
          RUFF_OUTPUT_FORMAT: github
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          tox run -e ${{ matrix.tox_env }}
      - name: Archive documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: documentation
          path: doc/_build/html
          compression-level: 9
        if: ${{ matrix.tox_env == 'docs' }}
      - name: Print debug information
        run: cat .tox/${{ matrix.tox_env }}/log/*.log
        if: ${{ failure() }}
    strategy:
      fail-fast: false
      matrix:
        tox_env: [lint, docs]
